version: 3
services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    depends_on:
      - Netflix-API
      - DB-API
      - mongodb
    volumes:
      - ./ReverseProxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  Netflix-API:
    image:
    container_name: Netflix-API
    depends_on:
      - DB-API
      - mongodb
    volumes:
      - ./Netflix-API:/netflix
    command:
      ["./wait-for-it.sh", "DB-API:3000/healthCheck", "--", "python", "app.py"]
    ports:
      - 10030:10010
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  DB-API:
    image:
    container_name: DB-API
    depends_on:
      - mongodb
    volumes:
      - ./DB-API:/DB-API
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  mongodb:
    image: mongo
    container_name: mongodb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    