version: "3"
networks:
    netflix:

services:
  kong-database:
    image: postgres:9.5
    container_name: kong-db
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    networks:
      - netflix
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  kong-migrations:
    image: kong:alpine
    command: kong migrations bootstrap && kong migrations up && kong migrations finish
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
    networks:
      - netflix
    restart: on-failure

  kong:
    image: kong:alpine
    container_name: kong-api
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    networks:
      - netflix
    ports:
      - "8000:8000"
      - "8001:8001"
    healthcheck:
        test: ["CMD", "kong", "health"]
        interval: 10s
        timeout: 10s
        retries: 10
    restart: on-failure

  netflix-api:
    image: xeno78/netflix-api:8
    environment:
        - VIRTUAL_HOST=netflixapi.local
        - VIRTUAL_PORT=10010
    container_name: netflix-api
    depends_on:
      - db-api
      - mongodb
    volumes:
      - ./Netflix-API:/netflix
    networks:
      - netflix
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
  db-api:
    image: xeno78/db-api:6
    container_name: db-api
    depends_on:
      - mongodb
    networks:
      - netflix
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - netflix
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3