version: "3"
networks:
    netflix:

services:
  kong-database:
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  kong-migrations:
    command: kong migrations bootstrap && kong migrations up && kong migrations finish
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_DATABASE: ${DB_NAME}
      KONG_PG_USER: ${DB_USER}
      KONG_PG_PASSWORD: ${DB_PASSWORD}
    restart: on-failure

  kong:
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_DATABASE: ${DB_NAME}
      KONG_PG_USER: ${DB_USER}
      KONG_PG_PASSWORD: ${DB_PASSWORD}
      KONG_ADMIN_LISTEN: 0.0.0.0:${ADMIN_PORT}
    ports:
      - "80:8000"
      - "${PUBLIC_ADMIN_PORT}:${ADMIN_PORT}"
    healthcheck:
        test: ["CMD", "kong", "health"]
        interval: 10s
        timeout: 10s
        retries: 10
    restart: on-failure

  netflix-api_1:
    environment:
        - VIRTUAL_HOST=netflixapi.local
        - VIRTUAL_PORT=10010
    volumes:
      - ./Netflix-API:/netflix
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: netflix.access
        
  netflix-api_2:
    environment:
        - VIRTUAL_HOST=netflixapi.local
        - VIRTUAL_PORT=10010
    volumes:
      - ./Netflix-API:/netflix
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: netflix.access

        
  db-api:
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  mongodb:
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      interval: 10s
      timeout: 20s
      retries: 5

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    container_name: fluentd
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - netflix

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: es01
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - netflix
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=false
      - cluster.initial_master_nodes=es01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.4
    container_name: kib01
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - netflix