version: "3"
networks:
    netflix:

services:
  kong-database:
    image: postgres:9.5
    container_name: kong-db
    networks:
      - netflix
    cpu_count: 2
    cpu_percent: 50
    cpus: 0.5
    cpuset: 0,1
    mem_limit: 1000000000
    memswap_limit: 2000000000

  kong-migrations:
    image: kong:alpine
    depends_on:
      kong-database:
        condition: service_healthy
    networks:
      - netflix
    cpu_count: 2
    cpu_percent: 50
    cpus: 0.5
    cpuset: 0,1
    mem_limit: 1000000000
    memswap_limit: 2000000000

  kong:
    image: kong:alpine
    container_name: kong-api
    depends_on:
      kong-database:
        condition: service_healthy
    networks:
      - netflix
    cpu_count: 2
    cpu_percent: 50
    cpus: 0.5
    cpuset: 0,1
    mem_limit: 1000000000
    memswap_limit: 2000000000

  netflix-api_1:
    image: xeno78/netflix-api:${NETFLIX_API_VERSION}
    container_name: netflix-api_1
    depends_on:
      - db-api
      - mongodb
    networks:
      - netflix
    cpu_count: 2
    cpu_percent: 50
    cpus: 0.5
    cpuset: 0,1
    mem_limit: 1000000000
    memswap_limit: 2000000000

  netflix-api_2:
    image: xeno78/netflix-api:${NETFLIX_API_VERSION}
    container_name: netflix-api_2
    depends_on:
      - db-api
      - mongodb
    networks:
      - netflix
    cpu_count: 2
    cpu_percent: 50
    cpus: 0.5
    cpuset: 0,1
    mem_limit: 1000000000
    memswap_limit: 2000000000

  db-api:
    image: xeno78/db-api:${DB_API_VERSION}
    container_name: db-api
    depends_on:
      - mongodb
    networks:
      - netflix
    cpu_count: 2
    cpu_percent: 50
    cpus: 0.5
    cpuset: 0,1
    mem_limit: 1000000000
    memswap_limit: 2000000000

  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - netflix
    cpu_count: 2
    cpu_percent: 50
    cpus: 0.5
    cpuset: 0,1
    mem_limit: 1000000000
    memswap_limit: 2000000000