version: "3"
networks:
    default:
        name: netflix
services:
  reverse-proxy:
    image: jwilder/nginx-proxy
    environment:
        - DEFAULT_HOST=netflixapi.local
    container_name: reverse-proxy
    depends_on:
      - Netflix-API
      - DB-API
      - mongodb
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    network_mode: netflix
  Netflix-API:
    image: xeno78/netflix-api:5
    environment:
        - VIRTUAL_HOST=netflixapi.local
        - VIRTUAL_PORT=10010
    container_name: Netflix-API
    depends_on:
      - DB-API
      - mongodb
    volumes:
      - ./Netflix-API:/netflix
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  DB-API:
    image: xeno78/db-api:4
    container_name: DB-API
    depends_on:
      - mongodb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  mongodb:
    image: mongo
    container_name: mongodb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    